name: Posit Issue
description: File a Posit Issue.
title: "[Issue]: "
labels: ["triage"]
projects: ["azl-data-science/Posit Problems"]
assignees:
  - "JoleneXiaoAZL,JaffarSyedAZL"
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Please complete the form and upload a screenshot of the issue.
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      value: "Describe the Posit issue, including error messages and timestamps."
    validations:
      required: true
  - type: checkboxes
    id: which-application
    attributes:
      label: Which Application?
      description: You may select more than one.
      options:
        - label: Workbench
        - label: Workbench 2 / Package Manager
        - label: Connect DEV
        - label: Connect PROD
      required: true


